// <auto-generated />
namespace CG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedtoursrating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedtoursrating));
        
        string IMigrationMetadata.Id
        {
            get { return "201605021412115_Added tours rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
