// <auto-generated />
namespace CG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changedtransporthandlingmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedtransporthandlingmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201605221049531_Changed transport handling method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
