// <auto-generated />
namespace CG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomObjectiveTourtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomObjectiveTourtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201605240622356_Custom ObjectiveTour table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
