// <auto-generated />
namespace CG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Addedinfototransporttour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedinfototransporttour));
        
        string IMigrationMetadata.Id
        {
            get { return "201607111600458_Added info to transport tour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
